In [64]:
import pandas as pd
import dask.dataframe as dd
from datetime import datetime

## Creating dfs by century

### Make df for 2000+ only

In [38]:
df = dd.read_csv('drought1_9/*.csv', usecols=['STATION','DATE','PRCP'])  # read all csv files in directory lazily
df.compute().to_csv('out2000.csv', index=False)  # convert to pandas and save as csv

In [45]:
df_2000 = pd.read_csv('out2000.csv')

In [46]:
df_2000['DATE'] = pd.to_datetime(df_2000['DATE'])

### Make df for 1900-1999

In [52]:
df = dd.read_csv('drought11_48/*.csv', usecols=['STATION','DATE','PRCP'])  # read all csv files in directory lazily
df.compute().to_csv('out1900.csv', index=False)  # convert to pandas and save as csv

In [99]:
df_1900 = pd.read_csv('out1900.csv')

In [100]:
df_1900['DATE'] = pd.to_datetime(df_1900['DATE'])

In [113]:
df_1900['DATE'] = df_1900['DATE'].dt.strftime('19%y-%m-%d')

### Make df for 1800-1899

In [119]:
df = dd.read_csv('drought50_52/*.csv', usecols=['STATION','DATE','PRCP'])  # read all csv files in directory lazily
df.compute().to_csv('out1800.csv', index=False)  # convert to pandas and save as csv

In [120]:
df_1800 = pd.read_csv('out1800.csv')

In [123]:
df_1800['DATE'] = pd.to_datetime(df_1800['DATE'])

## Handling overlapping date csv's

#### Overlapping 1997-2000

In [130]:
overlap1 = pd.read_csv('drought_data/10.csv', usecols=['STATION', 'DATE', 'PRCP'])

In [131]:
overlap1['DATE'] = pd.to_datetime(overlap1['DATE'])

In [136]:
# overlap1[(overlap1['DATE'].dt.year < 1999)]

#### Overlapping 1899-1901

In [140]:
overlap2 = pd.read_csv('drought_data/49.csv', usecols=['STATION', 'DATE', 'PRCP'])

In [141]:
overlap2['DATE'] = pd.to_datetime(overlap2['DATE'])

In [146]:
# overlap2[(overlap2['DATE'].dt.year < 1900)]

## Joining all dfs

In [147]:
combined_df = pd.concat([df_2000, df_1900], ignore_index=True)

In [157]:
combined_df.shape

(223895, 3)

In [158]:
combined_df = pd.concat([combined_df, df_1800], ignore_index=True)

In [159]:
combined_df.shape

(227926, 3)

In [160]:
combined_df = pd.concat([combined_df, overlap1], ignore_index=True)

In [161]:
combined_df = pd.concat([combined_df, overlap2], ignore_index=True)

In [162]:
combined_df.shape

(232574, 3)

In [163]:
combined_df

            STATION                 DATE  PRCP
0       US1TXCML006  2017-05-01 00:00:00  0.00
1       US1TXCML006  2017-05-02 00:00:00  0.00
2       US1TXCML006  2017-05-03 00:00:00  0.00
3       US1TXCML006  2017-05-04 00:00:00  0.00
4       US1TXCML006  2017-05-05 00:00:00  0.00
5       US1TXCML006  2017-05-06 00:00:00  0.00
6       US1TXCML006  2017-05-07 00:00:00  0.00
7       US1TXCML006  2017-05-08 00:00:00  0.00
8       US1TXCML006  2017-05-09 00:00:00  0.00
9       US1TXCML006  2017-05-10 00:00:00  0.05
10      US1TXCML006  2017-05-11 00:00:00  0.00
11      US1TXCML006  2017-05-12 00:00:00  0.09
12      US1TXCML006  2017-05-13 00:00:00  0.00
13      US1TXCML006  2017-05-14 00:00:00  0.00
14      US1TXCML006  2017-05-15 00:00:00  0.00
15      US1TXCML006  2017-05-16 00:00:00  0.00
16      US1TXCML006  2017-05-17 00:00:00  0.08
17      US1TXCML006  2017-05-18 00:00:00  0.00
18      US1TXCML006  2017-05-19 00:00:00  0.00
19      US1TXCML006  2017-05-20 00:00:00  0.00
20      US1TXCML006  2017-05-22 00:00:00  0.25
21      US1TXCML006  2017-05-23 00:00:00  0.00
22      US1TXCML006  2017-05-24 00:00:00  0.00
23      US1TXCML006  2017-05-25 00:00:00  0.00
24      US1TXCML006  2017-05-26 00:00:00  0.00
25      US1TXCML006  2017-05-28 00:00:00  0.00
26      US1TXCML006  2017-05-29 00:00:00  0.19
27      US1TXCML006  2017-05-30 00:00:00  0.02
28      US1TXCML006  2017-05-31 00:00:00  0.23
29      US1TXCML006  2017-06-01 00:00:00  0.51
...             ...                  ...   ...
232544  USC00410902  1901-12-02 00:00:00  0.00
232545  USC00410902  1901-12-03 00:00:00  0.00
232546  USC00410902  1901-12-04 00:00:00  0.00
232547  USC00410902  1901-12-05 00:00:00  0.00
232548  USC00410902  1901-12-06 00:00:00  0.00
232549  USC00410902  1901-12-07 00:00:00  0.07
232550  USC00410902  1901-12-08 00:00:00  0.22
232551  USC00410902  1901-12-09 00:00:00  0.00
232552  USC00410902  1901-12-10 00:00:00  0.00
232553  USC00410902  1901-12-11 00:00:00  0.00
232554  USC00410902  1901-12-12 00:00:00  0.04
232555  USC00410902  1901-12-13 00:00:00  0.00
232556  USC00410902  1901-12-14 00:00:00  0.00
232557  USC00410902  1901-12-15 00:00:00  0.00
232558  USC00410902  1901-12-16 00:00:00  0.00
232559  USC00410902  1901-12-17 00:00:00  0.00
232560  USC00410902  1901-12-18 00:00:00  0.00
232561  USC00410902  1901-12-19 00:00:00  0.00
232562  USC00410902  1901-12-20 00:00:00  0.00
232563  USC00410902  1901-12-21 00:00:00  0.00
232564  USC00410902  1901-12-22 00:00:00  0.00
232565  USC00410902  1901-12-23 00:00:00  0.00
232566  USC00410902  1901-12-24 00:00:00  0.00
232567  USC00410902  1901-12-25 00:00:00  0.00
232568  USC00410902  1901-12-26 00:00:00  0.00
232569  USC00410902  1901-12-27 00:00:00  0.00
232570  USC00410902  1901-12-28 00:00:00  0.00
232571  USC00410902  1901-12-29 00:00:00  0.00
232572  USC00410902  1901-12-30 00:00:00  0.00
232573  USC00410902  1901-12-31 00:00:00  0.00

[232574 rows x 3 columns]

In [173]:
combined_df['DATE'] = pd.to_datetime(combined_df['DATE'], format='%Y-%m-%d')

In [175]:
combined_df

            STATION       DATE  PRCP
0       US1TXCML006 2017-05-01  0.00
1       US1TXCML006 2017-05-02  0.00
2       US1TXCML006 2017-05-03  0.00
3       US1TXCML006 2017-05-04  0.00
4       US1TXCML006 2017-05-05  0.00
5       US1TXCML006 2017-05-06  0.00
6       US1TXCML006 2017-05-07  0.00
7       US1TXCML006 2017-05-08  0.00
8       US1TXCML006 2017-05-09  0.00
9       US1TXCML006 2017-05-10  0.05
10      US1TXCML006 2017-05-11  0.00
11      US1TXCML006 2017-05-12  0.09
12      US1TXCML006 2017-05-13  0.00
13      US1TXCML006 2017-05-14  0.00
14      US1TXCML006 2017-05-15  0.00
15      US1TXCML006 2017-05-16  0.00
16      US1TXCML006 2017-05-17  0.08
17      US1TXCML006 2017-05-18  0.00
18      US1TXCML006 2017-05-19  0.00
19      US1TXCML006 2017-05-20  0.00
20      US1TXCML006 2017-05-22  0.25
21      US1TXCML006 2017-05-23  0.00
22      US1TXCML006 2017-05-24  0.00
23      US1TXCML006 2017-05-25  0.00
24      US1TXCML006 2017-05-26  0.00
25      US1TXCML006 2017-05-28  0.00
26      US1TXCML006 2017-05-29  0.19
27      US1TXCML006 2017-05-30  0.02
28      US1TXCML006 2017-05-31  0.23
29      US1TXCML006 2017-06-01  0.51
...             ...        ...   ...
232544  USC00410902 1901-12-02  0.00
232545  USC00410902 1901-12-03  0.00
232546  USC00410902 1901-12-04  0.00
232547  USC00410902 1901-12-05  0.00
232548  USC00410902 1901-12-06  0.00
232549  USC00410902 1901-12-07  0.07
232550  USC00410902 1901-12-08  0.22
232551  USC00410902 1901-12-09  0.00
232552  USC00410902 1901-12-10  0.00
232553  USC00410902 1901-12-11  0.00
232554  USC00410902 1901-12-12  0.04
232555  USC00410902 1901-12-13  0.00
232556  USC00410902 1901-12-14  0.00
232557  USC00410902 1901-12-15  0.00
232558  USC00410902 1901-12-16  0.00
232559  USC00410902 1901-12-17  0.00
232560  USC00410902 1901-12-18  0.00
232561  USC00410902 1901-12-19  0.00
232562  USC00410902 1901-12-20  0.00
232563  USC00410902 1901-12-21  0.00
232564  USC00410902 1901-12-22  0.00
232565  USC00410902 1901-12-23  0.00
232566  USC00410902 1901-12-24  0.00
232567  USC00410902 1901-12-25  0.00
232568  USC00410902 1901-12-26  0.00
232569  USC00410902 1901-12-27  0.00
232570  USC00410902 1901-12-28  0.00
232571  USC00410902 1901-12-29  0.00
232572  USC00410902 1901-12-30  0.00
232573  USC00410902 1901-12-31  0.00

[232574 rows x 3 columns]

In [176]:
combined_df.to_csv(r'/Users/kathrynsalts/codeup/capstone/Main_data_repo/precipitation.csv')